blank_issues_enabled: true
contact_links:
  - name: Discussions
    about: General discussions about Awesome GEE Community Catalog
    url: https://github.com/SaiDhanyaa/awesome-gee-community-datasets/discussions
  - name: Linkedin
    about: Find me on Linkedin
    url: https://www.linkedin.com/in/Dhanyapriya-somasundaram/
